import "./globals.css";
import ClientWrapper from "./ClientWrapper";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={false}>
    <body>
    <ClientWrapper> {children} </ClientWrapper>
    </body>
    </html>
  );
}
